Repository onflow/flow-go-sdk, pull requests merged in 2022-06, with the labels that each got.

#288 Add github actions for getting diff & calling refresh
  .github/workflows/call-refresh-doc.yml
Labels: Developer Tool Team

#293 Update to Cadence v0.24.1
  go.mod
  go.sum
Labels: Improvement

#294 Update Cadence v0.24.3
  go.mod
  go.sum
Labels: Bugfix

#297 Update to Cadence v0.24.4, allow passing JSON options
  access/grpc/convert.go
  access/grpc/convert_test.go
  access/grpc/grpc.go
  access/http/client_test.go
  access/http/convert.go
  access/http/convert_test.go
  access/http/http.go
  go.mod
  go.sum
  transaction.go
Labels: Feature, Improvement

#292 Cadence encoding workaround
  flow.go
  transaction.go
  transaction_test.go
Labels: Improvement, Developer Tool Team

#305 Allow Cadence Unstructured Static Types
  access/grpc/grpc.go
  access/http/http.go
Labels: Improvement, Developer Tool Team

#304 Update to Cadence 5a06fec82b4a
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: Improvement
