Repository onflow/flow-go-sdk, pull requests merged in 2022-09, with the labels that each got.

#318 [Crypto] fix KMS signing bug for long messages
  crypto/cloudkms/cloudkms_test.go
  crypto/cloudkms/signer.go
Labels: Bug, Bugfix

#319 Remove deprecated GH action
  .github/workflows/call-refresh-doc.yml
Labels: Documentation

#310 Update address generator to match the flow-go
  address.go
  flow.go
Labels: Improvement
