Repository onflow/flow-go-sdk, pull requests merged in 2022-04, with the labels that each got.

#259 Don't include year range in licence
  NOTICE
  account.go
  account_test.go
  address.go
  address_test.go
  block.go
  client/client.go
  client/client_test.go
  client/convert/protobuf.go
  client/convert/protobuf_test.go
  collection.go
  crypto/cloudkms/cloudkms.go
  crypto/cloudkms/signer.go
  crypto/crypto.go
  crypto/crypto_test.go
  crypto/hash.go
  decode.go
  decode_test.go
  doc.go
  event.go
  examples/add_account_key/main.go
  examples/cloudkms/main.go
  examples/create_account/main.go
  examples/deploy_contract/main.go
  examples/examples.go
  examples/execute_script/main.go
  examples/get_accounts/main.go
  examples/get_blocks/main.go
  examples/get_collection/main.go
  examples/get_events/main.go
  examples/storage_usage/main.go
  examples/transaction_arguments/main.go
  examples/transaction_signing/multi_party/main.go
  examples/transaction_signing/multi_party_multisig/main.go
  examples/transaction_signing/multi_party_two_authorizers/main.go
  examples/transaction_signing/single_party/main.go
  examples/transaction_signing/single_party_multisig/main.go
  examples/verify_events/main.go
  examples/verify_signature/user_signature/main.go
  examples/verify_signature/user_signature_validate_all/main.go
  examples/verify_signature/user_signature_validate_any/main.go
  flow.go
  sign.go
  templates/accounts.go
  templates/accounts_test.go
  test/entities.go
  test/greetings.go
  test/signer.go
  transaction.go
  transaction_test.go
Labels: Documentation

#263 Update broken link
  docs/index.mdx
Labels: Documentation

#266 [Crypto] general updates
  account.go
  account_test.go
  crypto/cloudkms/cloudkms.go
  crypto/cloudkms/signer.go
  crypto/crypto.go
  crypto/hash.go
  go.mod
  go.sum
  test/signer.go
Labels: Feature, Improvement

#265 Update Cadence changes to memory metering
  client/convert/protobuf.go
  decode_test.go
  go.mod
  go.sum
  transaction.go
Labels: Improvement

#255 Extract Cadence templates
  examples/Makefile
  examples/modify_account/main.go
  go.mod
  go.sum
  templates/accounts.go
Labels: Improvement
