Repository onflow/flow-go-sdk, pull requests merged in 2024-04, with the labels that each got.

#613 Upgrade `onflow/crypto` and clarify build details
  README.md
  go.mod
  go.sum
Labels: Documentation, Dependencies

#614 Update to Cadence v1.0.0-preview.19
  go.mod
  go.sum
Labels: Dependencies

#615 Update v0 to Cadence v0.42.10
  go.mod
  go.sum
Labels: Dependencies

#618 Update to Cadence v1.0.0-preview.20
  go.mod
  go.sum
Labels: Dependencies

#633 Fix panic when encoding transaction with empty arguments (`release/v0`)
  flow.go
  transaction.go
Labels: Bugfix

#632 Fix panic when encoding transaction with empty arguments
  flow.go
  transaction.go
Labels: Bugfix

#638 Remove the special `EVMLocation` location
  decode_test.go
  evm_location.go
Labels: Improvement

#636 add backwards compatible decoder into grpc and http client
  access/grpc/client.go
  access/grpc/grpc_test.go
  access/http/client.go
  access/http/client_test.go
Labels: Improvement

#640 Update to Cadence v1.0.0-preview.24
  access/http/convert_test.go
  event.go
  go.mod
  go.sum
Labels: Dependencies
