Repository onflow/flow-go-sdk, pull requests merged in 2024-01, with the labels that each got.

#557 Update to newest Cadence 1.0 preview
  go.mod
  go.sum
Labels: Dependencies

#558 add Crescendo Support
  access/grpc/client.go
  access/http/client.go
  flow.go
Labels: Cadence 1.0

#560 Update Cadence version
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: Technical Debt

#563 Merge Cadence 1.0 (aka "Stable Cadence") feature branch
  .github/workflows/ci.yml
  examples/deploy_contract/main.go
  examples/examples.go
  examples/send_transactions/main.go
  examples/storage_usage/main.go
  go.mod
  go.sum
  templates/accounts.go
  test/entities.go
Labels: Improvement
