Repository onflow/flow-go-sdk, pull requests merged in 2024-02, with the labels that each got.

#584 Update to Cadence v1.0.0-M8
  go.mod
  go.sum
Labels: Dependencies

#583 Add a custom location for `EVM` and register a `TypeID` Decoder
  decode_test.go
  evm_location.go
Labels: Feature

#578 Add WaitServer method
  access/grpc/client.go
Labels: Improvement
